/**
 * Criação de Contas
 * API de Criação de Contas.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: cadastro_api@orama.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class AssinaturaEletronica {
  
  @SerializedName("assinaturaEletronica")
  private String assinaturaEletronica = null;

  /**
   * Assinatura eletrônica do usuário.
   **/
  @ApiModelProperty(value = "Assinatura eletrônica do usuário.")
  public String getAssinaturaEletronica() {
    return assinaturaEletronica;
  }
  public void setAssinaturaEletronica(String assinaturaEletronica) {
    this.assinaturaEletronica = assinaturaEletronica;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssinaturaEletronica assinaturaEletronica = (AssinaturaEletronica) o;
    return (this.assinaturaEletronica == null ? assinaturaEletronica.assinaturaEletronica == null : this.assinaturaEletronica.equals(assinaturaEletronica.assinaturaEletronica));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.assinaturaEletronica == null ? 0: this.assinaturaEletronica.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssinaturaEletronica {\n");
    
    sb.append("  assinaturaEletronica: ").append(assinaturaEletronica).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
