/**
 * Criação de Contas
 * API de Criação de Contas.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cadastro_api@orama.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Mensagem de erro detalhada
 **/
@ApiModel(description = "Mensagem de erro detalhada")
public class Erro {
  
  @SerializedName("mensagem")
  private Object mensagem = null;

  /**
   * Conteúdo da mensagem de erro.
   **/
  @ApiModelProperty(value = "Conteúdo da mensagem de erro.")
  public Object getMensagem() {
    return mensagem;
  }
  public void setMensagem(Object mensagem) {
    this.mensagem = mensagem;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Erro erro = (Erro) o;
    return (this.mensagem == null ? erro.mensagem == null : this.mensagem.equals(erro.mensagem));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.mensagem == null ? 0: this.mensagem.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Erro {\n");
    
    sb.append("  mensagem: ").append(mensagem).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
