/**
 * Criação de Contas
 * API de Criação de Contas.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cadastro_api@orama.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.math.BigDecimal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class FrontEndStep {
  
  @SerializedName("step")
  private BigDecimal step = null;
  @SerializedName("platform")
  private String platform = null;

  /**
   * Número positivo inteiro para registrar qual 'step' do ponto de vista de UI/front-end o Perfil se encontra.
   **/
  @ApiModelProperty(value = "Número positivo inteiro para registrar qual 'step' do ponto de vista de UI/front-end o Perfil se encontra.")
  public BigDecimal getStep() {
    return step;
  }
  public void setStep(BigDecimal step) {
    this.step = step;
  }

  /**
   * Representa o nome da plaforma do front-end.
   **/
  @ApiModelProperty(value = "Representa o nome da plaforma do front-end.")
  public String getPlatform() {
    return platform;
  }
  public void setPlatform(String platform) {
    this.platform = platform;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FrontEndStep frontEndStep = (FrontEndStep) o;
    return (this.step == null ? frontEndStep.step == null : this.step.equals(frontEndStep.step)) &&
        (this.platform == null ? frontEndStep.platform == null : this.platform.equals(frontEndStep.platform));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.step == null ? 0: this.step.hashCode());
    result = 31 * result + (this.platform == null ? 0: this.platform.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class FrontEndStep {\n");
    
    sb.append("  step: ").append(step).append("\n");
    sb.append("  platform: ").append(platform).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
