/**
 * Criação de Contas
 * API de Criação de Contas.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cadastro_api@orama.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class LoginObjeto {
  
  @SerializedName("nome")
  private String nome = null;
  @SerializedName("celular")
  private String celular = null;
  @SerializedName("cpf")
  private String cpf = null;
  @SerializedName("email")
  private String email = null;
  @SerializedName("dataNascimento")
  private Date dataNascimento = null;

  /**
   * Campo texto de preenchimento obrigatório para o preenchimento do nome completo do cliente.
   **/
  @ApiModelProperty(required = true, value = "Campo texto de preenchimento obrigatório para o preenchimento do nome completo do cliente.")
  public String getNome() {
    return nome;
  }
  public void setNome(String nome) {
    this.nome = nome;
  }

  /**
   * Telefone celular contendo o código de área e os nove digitos.
   **/
  @ApiModelProperty(required = true, value = "Telefone celular contendo o código de área e os nove digitos.")
  public String getCelular() {
    return celular;
  }
  public void setCelular(String celular) {
    this.celular = celular;
  }

  /**
   * CPF deve ser válido e não ter sido usado anteriormente. O CPF tem que ter os 11 dígitos com a máscara incluindo os pontos e hífen.
   **/
  @ApiModelProperty(required = true, value = "CPF deve ser válido e não ter sido usado anteriormente. O CPF tem que ter os 11 dígitos com a máscara incluindo os pontos e hífen.")
  public String getCpf() {
    return cpf;
  }
  public void setCpf(String cpf) {
    this.cpf = cpf;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   * Data de nascimento da pessoa no formato YYYY-MM-DD (cf. RFC 3339, section 5.8)
   **/
  @ApiModelProperty(required = true, value = "Data de nascimento da pessoa no formato YYYY-MM-DD (cf. RFC 3339, section 5.8)")
  public Date getDataNascimento() {
    return dataNascimento;
  }
  public void setDataNascimento(Date dataNascimento) {
    this.dataNascimento = dataNascimento;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoginObjeto loginObjeto = (LoginObjeto) o;
    return (this.nome == null ? loginObjeto.nome == null : this.nome.equals(loginObjeto.nome)) &&
        (this.celular == null ? loginObjeto.celular == null : this.celular.equals(loginObjeto.celular)) &&
        (this.cpf == null ? loginObjeto.cpf == null : this.cpf.equals(loginObjeto.cpf)) &&
        (this.email == null ? loginObjeto.email == null : this.email.equals(loginObjeto.email)) &&
        (this.dataNascimento == null ? loginObjeto.dataNascimento == null : this.dataNascimento.equals(loginObjeto.dataNascimento));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.nome == null ? 0: this.nome.hashCode());
    result = 31 * result + (this.celular == null ? 0: this.celular.hashCode());
    result = 31 * result + (this.cpf == null ? 0: this.cpf.hashCode());
    result = 31 * result + (this.email == null ? 0: this.email.hashCode());
    result = 31 * result + (this.dataNascimento == null ? 0: this.dataNascimento.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoginObjeto {\n");
    
    sb.append("  nome: ").append(nome).append("\n");
    sb.append("  celular: ").append(celular).append("\n");
    sb.append("  cpf: ").append(cpf).append("\n");
    sb.append("  email: ").append(email).append("\n");
    sb.append("  dataNascimento: ").append(dataNascimento).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
