/**
 * Criação de Contas
 * API de Criação de Contas.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: cadastro_api@orama.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Submetido {
  
  @SerializedName("submetido")
  private Boolean submetido = null;

  /**
   * Estado de submissão do perfil, true caso já tenha sido submetido, false caso contrário.
   **/
  @ApiModelProperty(value = "Estado de submissão do perfil, true caso já tenha sido submetido, false caso contrário.")
  public Boolean getSubmetido() {
    return submetido;
  }
  public void setSubmetido(Boolean submetido) {
    this.submetido = submetido;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Submetido submetido = (Submetido) o;
    return (this.submetido == null ? submetido.submetido == null : this.submetido.equals(submetido.submetido));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.submetido == null ? 0: this.submetido.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Submetido {\n");
    
    sb.append("  submetido: ").append(submetido).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
